name: nagish
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  avatar_glow: ^3.0.1
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  font_awesome_flutter: ^10.7.0
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1
  jitsi_meet: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.png